`timescale 1ns / 1ps

module XTimeTestBench;
    reg clk;
    reg rst;
    reg [0:7] input_byte;
    wire [0:7] output_byte;
    
    XTime xtime(.input_byte(input_byte),
                .output_byte(output_byte)
                );
    
    initial begin
        clk = 0;
        rst = 0;
        @(posedge clk);
        @(posedge clk);
        rst = 1;
        @(posedge clk);
        @(posedge clk);
        rst = 0;
        @(posedge clk);
        @(posedge clk);
        
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd168;
        assert (output_byte == 8'd75);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd168;
        assert (output_byte == 8'd75);
        @(posedge clk);
        input_byte = 8'd168;
        assert (output_byte == 8'd75);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd168;
        assert (output_byte == 8'd75);
        @(posedge clk);
        input_byte = 8'd168;
        assert (output_byte == 8'd75);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd168;
        assert (output_byte == 8'd75);
        @(posedge clk);
        input_byte = 8'd168;
        assert (output_byte == 8'd75);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd168;
        assert (output_byte == 8'd75);
        @(posedge clk);
        input_byte = 8'd5;
        assert (output_byte == 8'd10);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd1;
        assert (output_byte == 8'd2);
        @(posedge clk);
        input_byte = 8'd4;
        assert (output_byte == 8'd8);
        @(posedge clk);
        input_byte = 8'd5;
        assert (output_byte == 8'd10);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd1;
        assert (output_byte == 8'd2);
        @(posedge clk);
        input_byte = 8'd4;
        assert (output_byte == 8'd8);
        @(posedge clk);
        input_byte = 8'd5;
        assert (output_byte == 8'd10);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd1;
        assert (output_byte == 8'd2);
        @(posedge clk);
        input_byte = 8'd4;
        assert (output_byte == 8'd8);
        @(posedge clk);
        input_byte = 8'd5;
        assert (output_byte == 8'd10);
        @(posedge clk);
        input_byte = 8'd0;
        assert (output_byte == 8'd0);
        @(posedge clk);
        input_byte = 8'd1;
        assert (output_byte == 8'd2);
        @(posedge clk);
        input_byte = 8'd4;
        assert (output_byte == 8'd8);
        @(posedge clk);
        input_byte = 8'd39;
        assert (output_byte == 8'd78);
        @(posedge clk);
        input_byte = 8'd195;
        assert (output_byte == 8'd157);
        @(posedge clk);
        input_byte = 8'd130;
        assert (output_byte == 8'd31);
        @(posedge clk);
        input_byte = 8'd102;
        assert (output_byte == 8'd204);
        @(posedge clk);
        input_byte = 8'd8;
        assert (output_byte == 8'd16);
        @(posedge clk);
        input_byte = 8'd148;
        assert (output_byte == 8'd51);
        @(posedge clk);
        input_byte = 8'd71;
        assert (output_byte == 8'd142);
        @(posedge clk);
        input_byte = 8'd219;
        assert (output_byte == 8'd173);
        @(posedge clk);
        input_byte = 8'd39;
        assert (output_byte == 8'd78);
        @(posedge clk);
        input_byte = 8'd195;
        assert (output_byte == 8'd157);
        @(posedge clk);
        input_byte = 8'd130;
        assert (output_byte == 8'd31);
        @(posedge clk);
        input_byte = 8'd102;
        assert (output_byte == 8'd204);
        @(posedge clk);
        input_byte = 8'd8;
        assert (output_byte == 8'd16);
        @(posedge clk);
        input_byte = 8'd148;
        assert (output_byte == 8'd51);
        @(posedge clk);
        input_byte = 8'd71;
        assert (output_byte == 8'd142);
        @(posedge clk);
        input_byte = 8'd219;
        assert (output_byte == 8'd173);
        @(posedge clk);
        input_byte = 8'd117;
        assert (output_byte == 8'd234);
        @(posedge clk);
        input_byte = 8'd2;
        assert (output_byte == 8'd4);
        @(posedge clk);
        input_byte = 8'd58;
        assert (output_byte == 8'd116);
        @(posedge clk);
        input_byte = 8'd77;
        assert (output_byte == 8'd154);
        @(posedge clk);
        input_byte = 8'd117;
        assert (output_byte == 8'd234);
        @(posedge clk);
        input_byte = 8'd188;
        assert (output_byte == 8'd99);
        @(posedge clk);
        input_byte = 8'd69;
        assert (output_byte == 8'd138);
        @(posedge clk);
        input_byte = 8'd140;
        assert (output_byte == 8'd3);
        @(posedge clk);
        input_byte = 8'd117;
        assert (output_byte == 8'd234);
        @(posedge clk);
        input_byte = 8'd2;
        assert (output_byte == 8'd4);
        @(posedge clk);
        input_byte = 8'd58;
        assert (output_byte == 8'd116);
        @(posedge clk);
        input_byte = 8'd77;
        assert (output_byte == 8'd154);
        @(posedge clk);
        input_byte = 8'd117;
        assert (output_byte == 8'd234);
        @(posedge clk);
        input_byte = 8'd188;
        assert (output_byte == 8'd99);
        @(posedge clk);
        input_byte = 8'd69;
        assert (output_byte == 8'd138);
        @(posedge clk);
        input_byte = 8'd140;
        assert (output_byte == 8'd3);
        @(posedge clk);
        input_byte = 8'd115;
        assert (output_byte == 8'd230);
        @(posedge clk);
        input_byte = 8'd166;
        assert (output_byte == 8'd87);
        @(posedge clk);
        input_byte = 8'd229;
        assert (output_byte == 8'd209);
        @(posedge clk);
        input_byte = 8'd48;
        assert (output_byte == 8'd96);
        @(posedge clk);
        input_byte = 8'd78;
        assert (output_byte == 8'd156);
        @(posedge clk);
        input_byte = 8'd120;
        assert (output_byte == 8'd240);
        @(posedge clk);
        input_byte = 8'd129;
        assert (output_byte == 8'd25);
        @(posedge clk);
        input_byte = 8'd183;
        assert (output_byte == 8'd117);
        @(posedge clk);
        input_byte = 8'd228;
        assert (output_byte == 8'd211);
        @(posedge clk);
        input_byte = 8'd87;
        assert (output_byte == 8'd174);
        @(posedge clk);
        input_byte = 8'd185;
        assert (output_byte == 8'd105);
        @(posedge clk);
        input_byte = 8'd10;
        assert (output_byte == 8'd20);
        @(posedge clk);
        input_byte = 8'd96;
        assert (output_byte == 8'd192);
        @(posedge clk);
        input_byte = 8'd253;
        assert (output_byte == 8'd225);
        @(posedge clk);
        input_byte = 8'd78;
        assert (output_byte == 8'd156);
        @(posedge clk);
        input_byte = 8'd211;
        assert (output_byte == 8'd189);
        @(posedge clk);
        input_byte = 8'd202;
        assert (output_byte == 8'd143);
        @(posedge clk);
        input_byte = 8'd67;
        assert (output_byte == 8'd134);
        @(posedge clk);
        input_byte = 8'd97;
        assert (output_byte == 8'd194);
        @(posedge clk);
        input_byte = 8'd232;
        assert (output_byte == 8'd203);
        @(posedge clk);
        input_byte = 8'd71;
        assert (output_byte == 8'd142);
        @(posedge clk);
        input_byte = 8'd199;
        assert (output_byte == 8'd149);
        @(posedge clk);
        input_byte = 8'd99;
        assert (output_byte == 8'd198);
        @(posedge clk);
        input_byte = 8'd227;
        assert (output_byte == 8'd221);
        @(posedge clk);
        input_byte = 8'd200;
        assert (output_byte == 8'd139);
        @(posedge clk);
        input_byte = 8'd187;
        assert (output_byte == 8'd109);
        @(posedge clk);
        input_byte = 8'd77;
        assert (output_byte == 8'd154);
        @(posedge clk);
        input_byte = 8'd62;
        assert (output_byte == 8'd124);
        @(posedge clk);
        input_byte = 8'd177;
        assert (output_byte == 8'd121);
        @(posedge clk);
        input_byte = 8'd131;
        assert (output_byte == 8'd29);
        @(posedge clk);
        input_byte = 8'd62;
        assert (output_byte == 8'd124);
        @(posedge clk);
        input_byte = 8'd12;
        assert (output_byte == 8'd24);
        @(posedge clk);
        input_byte = 8'd127;
        assert (output_byte == 8'd254);
        @(posedge clk);
        input_byte = 8'd76;
        assert (output_byte == 8'd152);
        @(posedge clk);
        input_byte = 8'd241;
        assert (output_byte == 8'd249);
        @(posedge clk);
        input_byte = 8'd194;
        assert (output_byte == 8'd159);
        @(posedge clk);
        input_byte = 8'd22;
        assert (output_byte == 8'd44);
        @(posedge clk);
        input_byte = 8'd12;
        assert (output_byte == 8'd24);
        @(posedge clk);
        input_byte = 8'd157;
        assert (output_byte == 8'd33);
        @(posedge clk);
        input_byte = 8'd135;
        assert (output_byte == 8'd21);
        @(posedge clk);
        input_byte = 8'd103;
        assert (output_byte == 8'd206);
        @(posedge clk);
        input_byte = 8'd77;
        assert (output_byte == 8'd154);
        @(posedge clk);
        input_byte = 8'd125;
        assert (output_byte == 8'd250);
        @(posedge clk);
        input_byte = 8'd87;
        assert (output_byte == 8'd174);
        @(posedge clk);
        input_byte = 8'd131;
        assert (output_byte == 8'd29);
        @(posedge clk);
        input_byte = 8'd46;
        assert (output_byte == 8'd92);
        @(posedge clk);
        input_byte = 8'd253;
        assert (output_byte == 8'd225);
        @(posedge clk);
        input_byte = 8'd80;
        assert (output_byte == 8'd160);
        @(posedge clk);
        input_byte = 8'd102;
        assert (output_byte == 8'd204);
        @(posedge clk);
        input_byte = 8'd82;
        assert (output_byte == 8'd164);
        @(posedge clk);
        input_byte = 8'd48;
        assert (output_byte == 8'd96);
        @(posedge clk);
        input_byte = 8'd4;
        assert (output_byte == 8'd8);
        @(posedge clk);
        input_byte = 8'd241;
        assert (output_byte == 8'd249);
        @(posedge clk);
        input_byte = 8'd42;
        assert (output_byte == 8'd84);
        @(posedge clk);
        input_byte = 8'd65;
        assert (output_byte == 8'd130);
        @(posedge clk);
        input_byte = 8'd154;
        assert (output_byte == 8'd47);
        @(posedge clk);
        input_byte = 8'd119;
        assert (output_byte == 8'd238);
        @(posedge clk);
        input_byte = 8'd8;
        assert (output_byte == 8'd16);
        @(posedge clk);
        input_byte = 8'd136;
        assert (output_byte == 8'd11);
        @(posedge clk);
        input_byte = 8'd247;
        assert (output_byte == 8'd245);
        @(posedge clk);
        input_byte = 8'd14;
        assert (output_byte == 8'd28);
        @(posedge clk);
        input_byte = 8'd22;
        assert (output_byte == 8'd44);
        @(posedge clk);
        input_byte = 8'd182;
        assert (output_byte == 8'd119);
        @(posedge clk);
        input_byte = 8'd174;
        assert (output_byte == 8'd71);
        @(posedge clk);
        input_byte = 8'd57;
        assert (output_byte == 8'd114);
        @(posedge clk);
        input_byte = 8'd65;
        assert (output_byte == 8'd130);
        @(posedge clk);
        input_byte = 8'd251;
        assert (output_byte == 8'd237);
        @(posedge clk);
        input_byte = 8'd131;
        assert (output_byte == 8'd29);
        @(posedge clk);
        input_byte = 8'd76;
        assert (output_byte == 8'd152);
        @(posedge clk);
        input_byte = 8'd196;
        assert (output_byte == 8'd147);
        @(posedge clk);
        input_byte = 8'd113;
        assert (output_byte == 8'd226);
        @(posedge clk);
        input_byte = 8'd249;
        assert (output_byte == 8'd233);
        @(posedge clk);
        input_byte = 8'd98;
        assert (output_byte == 8'd196);
        @(posedge clk);
        input_byte = 8'd220;
        assert (output_byte == 8'd163);
        @(posedge clk);
        input_byte = 8'd67;
        assert (output_byte == 8'd134);
        @(posedge clk);
        input_byte = 8'd253;
        assert (output_byte == 8'd225);
        @(posedge clk);
        input_byte = 8'd138;
        assert (output_byte == 8'd15);
        @(posedge clk);
        input_byte = 8'd115;
        assert (output_byte == 8'd230);
        @(posedge clk);
        input_byte = 8'd143;
        assert (output_byte == 8'd5);
        @(posedge clk);
        input_byte = 8'd118;
        assert (output_byte == 8'd236);
        @(posedge clk);
        input_byte = 8'd33;
        assert (output_byte == 8'd66);
        @(posedge clk);
        input_byte = 8'd28;
        assert (output_byte == 8'd56);
        @(posedge clk);
        input_byte = 8'd188;
        assert (output_byte == 8'd99);
        @(posedge clk);
        input_byte = 8'd129;
        assert (output_byte == 8'd25);
        @(posedge clk);
        input_byte = 8'd22;
        assert (output_byte == 8'd44);
        @(posedge clk);
        input_byte = 8'd235;
        assert (output_byte == 8'd205);
        @(posedge clk);
        input_byte = 8'd74;
        assert (output_byte == 8'd148);
        @(posedge clk);
        input_byte = 8'd183;
        assert (output_byte == 8'd117);
        @(posedge clk);
        input_byte = 8'd96;
        assert (output_byte == 8'd192);
        @(posedge clk);
        input_byte = 8'd14;
        assert (output_byte == 8'd28);
        @(posedge clk);
        input_byte = 8'd162;
        assert (output_byte == 8'd95);
        @(posedge clk);
        input_byte = 8'd204;
        assert (output_byte == 8'd131);
        @(posedge clk);
        input_byte = 8'd105;
        assert (output_byte == 8'd210);
        @(posedge clk);
        input_byte = 8'd210;
        assert (output_byte == 8'd191);
        @(posedge clk);
        input_byte = 8'd206;
        assert (output_byte == 8'd135);
        @(posedge clk);
        input_byte = 8'd117;
        assert (output_byte == 8'd234);
        @(posedge clk);
        input_byte = 8'd233;
        assert (output_byte == 8'd201);
        @(posedge clk);
        input_byte = 8'd18;
        assert (output_byte == 8'd36);
        @(posedge clk);
        input_byte = 8'd247;
        assert (output_byte == 8'd245);
        @(posedge clk);
        input_byte = 8'd12;
        assert (output_byte == 8'd24);
        @(posedge clk);
        input_byte = 8'd48;
        assert (output_byte == 8'd96);
        @(posedge clk);
        input_byte = 8'd16;
        assert (output_byte == 8'd32);
        @(posedge clk);
        input_byte = 8'd1;
        assert (output_byte == 8'd2);
        @(posedge clk);
        input_byte = 8'd33;
        assert (output_byte == 8'd66);
        @(posedge clk);
        input_byte = 8'd124;
        assert (output_byte == 8'd248);
        @(posedge clk);
        input_byte = 8'd33;
        assert (output_byte == 8'd66);
        @(posedge clk);
        input_byte = 8'd121;
        assert (output_byte == 8'd242);
        @(posedge clk);
        input_byte = 8'd36;
        assert (output_byte == 8'd72);
        @(posedge clk);
        input_byte = 8'd31;
        assert (output_byte == 8'd62);
        @(posedge clk);
        input_byte = 8'd168;
        assert (output_byte == 8'd75);
        @(posedge clk);
        input_byte = 8'd255;
        assert (output_byte == 8'd229);
        @(posedge clk);
        input_byte = 8'd72;
        assert (output_byte == 8'd144);
        
        @(posedge clk);
        input_byte = 8'd255;
        assert (output_byte == 8'd229);
        @(posedge clk);
        input_byte = 8'd55;
        assert (output_byte == 8'd110);
        @(posedge clk);
        input_byte = 8'd51;
        assert (output_byte == 8'd102);
        @(posedge clk);
        input_byte = 8'd33;
        assert (output_byte == 8'd66);
        @(posedge clk);
        input_byte = 8'd109;
        assert (output_byte == 8'd218);
        @(posedge clk);
        input_byte = 8'd120;
        assert (output_byte == 8'd240);
        @(posedge clk);
        input_byte = 8'd52;
        assert (output_byte == 8'd104);
        @(posedge clk);
        input_byte = 8'd182;
        assert (output_byte == 8'd119);
        @(posedge clk);
        input_byte = 8'd206;
        assert (output_byte == 8'd135);
        @(posedge clk);
        input_byte = 8'd226;
        assert (output_byte == 8'd223);
        @(posedge clk);
        input_byte = 8'd154;
        assert (output_byte == 8'd47);
        @(posedge clk);
        input_byte = 8'd9;
        assert (output_byte == 8'd18);
        @(posedge clk);
        input_byte = 8'd51;
        assert (output_byte == 8'd102);
        @(posedge clk);
        input_byte = 8'd114;
        assert (output_byte == 8'd228);
        @(posedge clk);
        input_byte = 8'd72;
        assert (output_byte == 8'd144);
        @(posedge clk);
        input_byte = 8'd229;
        assert (output_byte == 8'd209);
        @(posedge clk);
        input_byte = 8'd116;
        assert (output_byte == 8'd232);
        @(posedge clk);
        input_byte = 8'd55;
        assert (output_byte == 8'd110);
        @(posedge clk);
        input_byte = 8'd166;
        assert (output_byte == 8'd87);
        @(posedge clk);
        input_byte = 8'd72;
        assert (output_byte == 8'd144);
        @(posedge clk);
        input_byte = 8'd223;
        assert (output_byte == 8'd165);
        @(posedge clk);
        input_byte = 8'd106;
        assert (output_byte == 8'd212);
        @(posedge clk);
        input_byte = 8'd253;
        assert (output_byte == 8'd225);
        @(posedge clk);
        input_byte = 8'd236;
        assert (output_byte == 8'd195);
        @(posedge clk);
        input_byte = 8'd12;
        assert (output_byte == 8'd24);
        @(posedge clk);
        input_byte = 8'd99;
        assert (output_byte == 8'd198);
        @(posedge clk);
        input_byte = 8'd131;
        assert (output_byte == 8'd29);
        @(posedge clk);
        input_byte = 8'd234;
        assert (output_byte == 8'd207);
        @(posedge clk);
        input_byte = 8'd62;
        assert (output_byte == 8'd124);
        @(posedge clk);
        input_byte = 8'd147;
        assert (output_byte == 8'd61);
        @(posedge clk);
        input_byte = 8'd71;
        assert (output_byte == 8'd142);
        @(posedge clk);
        input_byte = 8'd193;
        assert (output_byte == 8'd153);
        @(posedge clk);
        input_byte = 8'd22;
        assert (output_byte == 8'd44);
        @(posedge clk);
        input_byte = 8'd80;
        assert (output_byte == 8'd160);
        @(posedge clk);
        input_byte = 8'd135;
        assert (output_byte == 8'd21);
        @(posedge clk);
        input_byte = 8'd119;
        assert (output_byte == 8'd238);
        @(posedge clk);
        input_byte = 8'd89;
        assert (output_byte == 8'd178);
        @(posedge clk);
        input_byte = 8'd66;
        assert (output_byte == 8'd132);
        @(posedge clk);
        input_byte = 8'd108;
        assert (output_byte == 8'd216);
        @(posedge clk);
        input_byte = 8'd30;
        assert (output_byte == 8'd60);
        @(posedge clk);
        input_byte = 8'd78;
        assert (output_byte == 8'd156);
        @(posedge clk);
        input_byte = 8'd187;
        assert (output_byte == 8'd109);
        @(posedge clk);
        input_byte = 8'd235;
        assert (output_byte == 8'd205);
        @(posedge clk);
        input_byte = 8'd125;
        assert (output_byte == 8'd250);
        @(posedge clk);
        input_byte = 8'd49;
        assert (output_byte == 8'd98);
        @(posedge clk);
        input_byte = 8'd113;
        assert (output_byte == 8'd226);
        @(posedge clk);
        input_byte = 8'd61;
        assert (output_byte == 8'd122);
        @(posedge clk);
        input_byte = 8'd229;
        assert (output_byte == 8'd209);
        @(posedge clk);
        input_byte = 8'd98;
        assert (output_byte == 8'd196);
        @(posedge clk);
        input_byte = 8'd79;
        assert (output_byte == 8'd158);
        @(posedge clk);
        input_byte = 8'd200;
        assert (output_byte == 8'd139);
        @(posedge clk);
        input_byte = 8'd4;
        assert (output_byte == 8'd8);
        @(posedge clk);
        input_byte = 8'd245;
        assert (output_byte == 8'd241);
        @(posedge clk);
        input_byte = 8'd229;
        assert (output_byte == 8'd209);
        @(posedge clk);
        input_byte = 8'd20;
        assert (output_byte == 8'd40);
        @(posedge clk);
        input_byte = 8'd26;
        assert (output_byte == 8'd52);
        @(posedge clk);
        input_byte = 8'd186;
        assert (output_byte == 8'd111);
        @(posedge clk);
        input_byte = 8'd58;
        assert (output_byte == 8'd116);
        @(posedge clk);
        input_byte = 8'd154;
        assert (output_byte == 8'd47);
        @(posedge clk);
        input_byte = 8'd10;
        assert (output_byte == 8'd20);
        @(posedge clk);
        input_byte = 8'd56;
        assert (output_byte == 8'd112);
        @(posedge clk);
        input_byte = 8'd113;
        assert (output_byte == 8'd226);
        @(posedge clk);
        input_byte = 8'd67;
        assert (output_byte == 8'd134);
        @(posedge clk);
        input_byte = 8'd80;
        assert (output_byte == 8'd160);
        @(posedge clk);
        input_byte = 8'd164;
        assert (output_byte == 8'd83);
        @(posedge clk);
        input_byte = 8'd155;
        assert (output_byte == 8'd45);
        @(posedge clk);
        input_byte = 8'd111;
        assert (output_byte == 8'd222);
        @(posedge clk);
        input_byte = 8'd35;
        assert (output_byte == 8'd70);
        @(posedge clk);
        input_byte = 8'd86;
        assert (output_byte == 8'd172);
        @(posedge clk);
        input_byte = 8'd47;
        assert (output_byte == 8'd94);
        @(posedge clk);
        input_byte = 8'd90;
        assert (output_byte == 8'd180);
        @(posedge clk);
        input_byte = 8'd250;
        assert (output_byte == 8'd239);
        @(posedge clk);
        input_byte = 8'd45;
        assert (output_byte == 8'd90);
        @(posedge clk);
        input_byte = 8'd18;
        assert (output_byte == 8'd36);
        @(posedge clk);
        input_byte = 8'd197;
        assert (output_byte == 8'd145);
        @(posedge clk);
        input_byte = 8'd253;
        assert (output_byte == 8'd225);
        @(posedge clk);
        input_byte = 8'd112;
        assert (output_byte == 8'd224);
        @(posedge clk);
        input_byte = 8'd14;
        assert (output_byte == 8'd28);
        @(posedge clk);
        input_byte = 8'd131;
        assert (output_byte == 8'd29);
        @(posedge clk);
        input_byte = 8'd159;
        assert (output_byte == 8'd37);
        @(posedge clk);
        input_byte = 8'd204;
        assert (output_byte == 8'd131);
        @(posedge clk);
        input_byte = 8'd187;
        assert (output_byte == 8'd109);
        @(posedge clk);
        input_byte = 8'd232;
        assert (output_byte == 8'd203);
        @(posedge clk);
        input_byte = 8'd156;
        assert (output_byte == 8'd35);
        @(posedge clk);
        input_byte = 8'd72;
        assert (output_byte == 8'd144);
        @(posedge clk);
        input_byte = 8'd185;
        assert (output_byte == 8'd105);
        @(posedge clk);
        input_byte = 8'd109;
        assert (output_byte == 8'd218);
        @(posedge clk);
        input_byte = 8'd70;
        assert (output_byte == 8'd140);
        @(posedge clk);
        input_byte = 8'd220;
        assert (output_byte == 8'd163);
        @(posedge clk);
        input_byte = 8'd206;
        assert (output_byte == 8'd135);
        @(posedge clk);
        input_byte = 8'd84;
        assert (output_byte == 8'd168);
        @(posedge clk);
        input_byte = 8'd150;
        assert (output_byte == 8'd55);
        @(posedge clk);
        input_byte = 8'd11;
        assert (output_byte == 8'd22);
        @(posedge clk);
        input_byte = 8'd165;
        assert (output_byte == 8'd81);
        @(posedge clk);
        input_byte = 8'd56;
        assert (output_byte == 8'd112);
        @(posedge clk);
        input_byte = 8'd203;
        assert (output_byte == 8'd141);
        @(posedge clk);
        input_byte = 8'd142;
        assert (output_byte == 8'd7);
        @(posedge clk);
        input_byte = 8'd105;
        assert (output_byte == 8'd210);
        @(posedge clk);
        input_byte = 8'd44;
        assert (output_byte == 8'd88);
        @(posedge clk);
        input_byte = 8'd123;
        assert (output_byte == 8'd246);
        @(posedge clk);
        input_byte = 8'd27;
        assert (output_byte == 8'd54);
        @(posedge clk);
        input_byte = 8'd241;
        assert (output_byte == 8'd249);
        @(posedge clk);
        input_byte = 8'd145;
        assert (output_byte == 8'd57);
        @(posedge clk);
        input_byte = 8'd66;
        assert (output_byte == 8'd132);
        @(posedge clk);
        input_byte = 8'd201;
        assert (output_byte == 8'd137);
        @(posedge clk);
        input_byte = 8'd197;
        assert (output_byte == 8'd145);
        @(posedge clk);
        input_byte = 8'd78;
        assert (output_byte == 8'd156);
        @(posedge clk);
        input_byte = 8'd68;
        assert (output_byte == 8'd136);
        @(posedge clk);
        input_byte = 8'd28;
        assert (output_byte == 8'd56);
        @(posedge clk);
        input_byte = 8'd139;
        assert (output_byte == 8'd13);
        @(posedge clk);
        input_byte = 8'd211;
        assert (output_byte == 8'd189);
        @(posedge clk);
        input_byte = 8'd148;
        assert (output_byte == 8'd51);
        @(posedge clk);
        input_byte = 8'd40;
        assert (output_byte == 8'd80);
        @(posedge clk);
        input_byte = 8'd190;
        assert (output_byte == 8'd103);
        @(posedge clk);
        input_byte = 8'd2;
        assert (output_byte == 8'd4);
        @(posedge clk);
        input_byte = 8'd178;
        assert (output_byte == 8'd127);
        @(posedge clk);
        input_byte = 8'd242;
        assert (output_byte == 8'd255);
        @(posedge clk);
        input_byte = 8'd15;
        assert (output_byte == 8'd30);
        @(posedge clk);
        input_byte = 8'd79;
        assert (output_byte == 8'd158);
        @(posedge clk);
        input_byte = 8'd115;
        assert (output_byte == 8'd230);
        @(posedge clk);
        input_byte = 8'd217;
        assert (output_byte == 8'd169);
        @(posedge clk);
        input_byte = 8'd79;
        assert (output_byte == 8'd158);
        @(posedge clk);
        input_byte = 8'd229;
        assert (output_byte == 8'd209);
        @(posedge clk);
        input_byte = 8'd78;
        assert (output_byte == 8'd156);
        @(posedge clk);
        input_byte = 8'd10;
        assert (output_byte == 8'd20);
        @(posedge clk);
        input_byte = 8'd114;
        assert (output_byte == 8'd228);
        @(posedge clk);
        input_byte = 8'd54;
        assert (output_byte == 8'd108);
        @(posedge clk);
        input_byte = 8'd60;
        assert (output_byte == 8'd120);
        @(posedge clk);
        input_byte = 8'd5;
        assert (output_byte == 8'd10);
        @(posedge clk);
        input_byte = 8'd211;
        assert (output_byte == 8'd189);
        @(posedge clk);
        input_byte = 8'd234;
        assert (output_byte == 8'd207);
        @(posedge clk);
        input_byte = 8'd175;
        assert (output_byte == 8'd69);
        @(posedge clk);
        input_byte = 8'd55;
        assert (output_byte == 8'd110);
        @(posedge clk);
        input_byte = 8'd124;
        assert (output_byte == 8'd248);
        @(posedge clk);
        input_byte = 8'd228;
        assert (output_byte == 8'd211);
        @(posedge clk);
        input_byte = 8'd31;
        assert (output_byte == 8'd62);
        @(posedge clk);
        input_byte = 8'd140;
        assert (output_byte == 8'd3);
        @(posedge clk);
        input_byte = 8'd82;
        assert (output_byte == 8'd164);
        @(posedge clk);
        input_byte = 8'd193;
        assert (output_byte == 8'd153);
        @(posedge clk);
        input_byte = 8'd48;
        assert (output_byte == 8'd96);
        @(posedge clk);
        input_byte = 8'd179;
        assert (output_byte == 8'd125);
        @(posedge clk);
        input_byte = 8'd108;
        assert (output_byte == 8'd216);
        @(posedge clk);
        input_byte = 8'd239;
        assert (output_byte == 8'd197);
        @(posedge clk);
        input_byte = 8'd105;
        assert (output_byte == 8'd210);
        @(posedge clk);
        input_byte = 8'd129;
        assert (output_byte == 8'd25);
        @(posedge clk);
        input_byte = 8'd229;
        assert (output_byte == 8'd209);
        @(posedge clk);
        input_byte = 8'd13;
        assert (output_byte == 8'd26);
        @(posedge clk);
        input_byte = 8'd189;
        assert (output_byte == 8'd97);
        @(posedge clk);
        input_byte = 8'd199;
        assert (output_byte == 8'd149);
        @(posedge clk);
        input_byte = 8'd230;
        assert (output_byte == 8'd215);
        @(posedge clk);
        input_byte = 8'd156;
        assert (output_byte == 8'd35);
        @(posedge clk);
        input_byte = 8'd112;
        assert (output_byte == 8'd224);
        @(posedge clk);
        input_byte = 8'd26;
        assert (output_byte == 8'd52);
        @(posedge clk);
        input_byte = 8'd55;
        assert (output_byte == 8'd110);
        @(posedge clk);
        input_byte = 8'd93;
        assert (output_byte == 8'd186);
        @(posedge clk);
        input_byte = 8'd101;
        assert (output_byte == 8'd202);
        @(posedge clk);
        input_byte = 8'd28;
        assert (output_byte == 8'd56);
        @(posedge clk);
        input_byte = 8'd150;
        assert (output_byte == 8'd55);
        @(posedge clk);
        input_byte = 8'd239;
        assert (output_byte == 8'd197);
        @(posedge clk);
        input_byte = 8'd70;
        assert (output_byte == 8'd140);
        @(posedge clk);
        input_byte = 8'd200;
        assert (output_byte == 8'd139);
        @(posedge clk);
        input_byte = 8'd251;
        assert (output_byte == 8'd237);
        @(posedge clk);
        input_byte = 8'd117;
        assert (output_byte == 8'd234);
        @(posedge clk);
        input_byte = 8'd150;
        assert (output_byte == 8'd55);
        @(posedge clk);
        input_byte = 8'd113;
        assert (output_byte == 8'd226);
        @(posedge clk);
        input_byte = 8'd175;
        assert (output_byte == 8'd69);
        @(posedge clk);
        input_byte = 8'd72;
        assert (output_byte == 8'd144);
        @(posedge clk);
        input_byte = 8'd135;
        assert (output_byte == 8'd21);
        @(posedge clk);
        input_byte = 8'd87;
        assert (output_byte == 8'd174);
        @(posedge clk);
        input_byte = 8'd143;
        assert (output_byte == 8'd5);
        @(posedge clk);
        input_byte = 8'd95;
        assert (output_byte == 8'd190);
        @(posedge clk);
        input_byte = 8'd49;
        assert (output_byte == 8'd98);
        @(posedge clk);
        input_byte = 8'd226;
        assert (output_byte == 8'd223);
        @(posedge clk);
        input_byte = 8'd127;
        assert (output_byte == 8'd254);
        @(posedge clk);
        input_byte = 8'd172;
        assert (output_byte == 8'd67);
        @(posedge clk);
        input_byte = 8'd43;
        assert (output_byte == 8'd86);
        @(posedge clk);
        input_byte = 8'd186;
        assert (output_byte == 8'd111);
        @(posedge clk);
        input_byte = 8'd202;
        assert (output_byte == 8'd143);
        @(posedge clk);
        input_byte = 8'd91;
        assert (output_byte == 8'd182);
        @(posedge clk);
        input_byte = 8'd169;
        assert (output_byte == 8'd73);
        @(posedge clk);
        input_byte = 8'd26;
        assert (output_byte == 8'd52);
        @(posedge clk);
        input_byte = 8'd239;
        assert (output_byte == 8'd197);
        @(posedge clk);
        input_byte = 8'd92;
        assert (output_byte == 8'd184);
        @(posedge clk);
        input_byte = 8'd215;
        assert (output_byte == 8'd181);
        @(posedge clk);
        input_byte = 8'd168;
        assert (output_byte == 8'd75);
        @(posedge clk);
        input_byte = 8'd246;
        assert (output_byte == 8'd247);
        @(posedge clk);
        input_byte = 8'd137;
        assert (output_byte == 8'd9);
        @(posedge clk);
        input_byte = 8'd83;
        assert (output_byte == 8'd166);
        @(posedge clk);
        input_byte = 8'd239;
        assert (output_byte == 8'd197);
        @(posedge clk);
        input_byte = 8'd207;
        assert (output_byte == 8'd133);
        @(posedge clk);
        input_byte = 8'd115;
        assert (output_byte == 8'd230);
        @(posedge clk);
        input_byte = 8'd159;
        assert (output_byte == 8'd37);
        @(posedge clk);
        input_byte = 8'd246;
        assert (output_byte == 8'd247);
        @(posedge clk);
        input_byte = 8'd14;
        assert (output_byte == 8'd28);
        @(posedge clk);
        input_byte = 8'd103;
        assert (output_byte == 8'd206);
        @(posedge clk);
        input_byte = 8'd43;
        assert (output_byte == 8'd86);
        @(posedge clk);
        input_byte = 8'd203;
        assert (output_byte == 8'd141);
        @(posedge clk);
        input_byte = 8'd241;
        assert (output_byte == 8'd249);
        @(posedge clk);
        input_byte = 8'd17;
        assert (output_byte == 8'd34);
        @(posedge clk);
        input_byte = 8'd83;
        assert (output_byte == 8'd166);
        @(posedge clk);
        input_byte = 8'd63;
        assert (output_byte == 8'd126);
        @(posedge clk);
        input_byte = 8'd235;
        assert (output_byte == 8'd205);
        @(posedge clk);
        input_byte = 8'd135;
        assert (output_byte == 8'd21);
        @(posedge clk);
        input_byte = 8'd108;
        assert (output_byte == 8'd216);
        @(posedge clk);
        input_byte = 8'd86;
        assert (output_byte == 8'd172);
        @(posedge clk);
        input_byte = 8'd134;
        assert (output_byte == 8'd23);
        @(posedge clk);
        input_byte = 8'd188;
        assert (output_byte == 8'd99);
        @(posedge clk);
        input_byte = 8'd180;
        assert (output_byte == 8'd115);
        @(posedge clk);
        input_byte = 8'd164;
        assert (output_byte == 8'd83);
        @(posedge clk);
        input_byte = 8'd250;
        assert (output_byte == 8'd239);
        @(posedge clk);
        input_byte = 8'd234;
        assert (output_byte == 8'd207);
        @(posedge clk);
        input_byte = 8'd200;
        assert (output_byte == 8'd139);
        @(posedge clk);
        input_byte = 8'd216;
        assert (output_byte == 8'd171);
        @(posedge clk);
        input_byte = 8'd13;
        assert (output_byte == 8'd26);
        @(posedge clk);
        input_byte = 8'd29;
        assert (output_byte == 8'd58);
        @(posedge clk);
        input_byte = 8'd153;
        assert (output_byte == 8'd41);
        @(posedge clk);
        input_byte = 8'd138;
        assert (output_byte == 8'd15);
        @(posedge clk);
        input_byte = 8'd153;
        assert (output_byte == 8'd41);
        @(posedge clk);
        input_byte = 8'd138;
        assert (output_byte == 8'd15);
        @(posedge clk);
        input_byte = 8'd64;
        assert (output_byte == 8'd128);
        @(posedge clk);
        input_byte = 8'd20;
        assert (output_byte == 8'd40);
        @(posedge clk);
        input_byte = 8'd87;
        assert (output_byte == 8'd174);
        @(posedge clk);
        input_byte = 8'd3;
        assert (output_byte == 8'd6);
        @(posedge clk);
        input_byte = 8'd105;
        assert (output_byte == 8'd210);
        @(posedge clk);
        input_byte = 8'd40;
        assert (output_byte == 8'd80);
        @(posedge clk);
        input_byte = 8'd22;
        assert (output_byte == 8'd44);
        @(posedge clk);
        input_byte = 8'd87;
        assert (output_byte == 8'd174);
        @(posedge clk);
        input_byte = 8'd188;
        assert (output_byte == 8'd99);
        @(posedge clk);
        input_byte = 8'd42;
        assert (output_byte == 8'd84);
        @(posedge clk);
        input_byte = 8'd75;
        assert (output_byte == 8'd150);
        @(posedge clk);
        input_byte = 8'd221;
        assert (output_byte == 8'd161);
        @(posedge clk);
        input_byte = 8'd153;
        assert (output_byte == 8'd41);
        @(posedge clk);
        input_byte = 8'd242;
        assert (output_byte == 8'd255);
        @(posedge clk);
        input_byte = 8'd157;
        assert (output_byte == 8'd33);
        @(posedge clk);
        input_byte = 8'd246;
        assert (output_byte == 8'd247);
        @(posedge clk);
        input_byte = 8'd253;
        assert (output_byte == 8'd225);
        @(posedge clk);
        input_byte = 8'd35;
        assert (output_byte == 8'd70);
        @(posedge clk);
        input_byte = 8'd37;
        assert (output_byte == 8'd74);
        @(posedge clk);
        input_byte = 8'd251;
        assert (output_byte == 8'd237);
        @(posedge clk);
        input_byte = 8'd225;
        assert (output_byte == 8'd217);
        @(posedge clk);
        input_byte = 8'd253;
        assert (output_byte == 8'd225);
        @(posedge clk);
        input_byte = 8'd25;
        assert (output_byte == 8'd50);
        @(posedge clk);
        input_byte = 8'd5;
        assert (output_byte == 8'd10);
        @(posedge clk);
        input_byte = 8'd229;
        assert (output_byte == 8'd209);
        @(posedge clk);
        input_byte = 8'd30;
        assert (output_byte == 8'd60);
        @(posedge clk);
        input_byte = 8'd49;
        assert (output_byte == 8'd98);
        @(posedge clk);
        input_byte = 8'd202;
        assert (output_byte == 8'd143);
        @(posedge clk);
        input_byte = 8'd41;
        assert (output_byte == 8'd82);
        @(posedge clk);
        input_byte = 8'd243;
        assert (output_byte == 8'd253);
        @(posedge clk);
        input_byte = 8'd122;
        assert (output_byte == 8'd244);
        @(posedge clk);
        input_byte = 8'd160;
        assert (output_byte == 8'd91);
        @(posedge clk);
        input_byte = 8'd22;
        assert (output_byte == 8'd44);
        @(posedge clk);
        input_byte = 8'd130;
        assert (output_byte == 8'd31);
        @(posedge clk);
        input_byte = 8'd157;
        assert (output_byte == 8'd33);
        @(posedge clk);
        input_byte = 8'd9;
        assert (output_byte == 8'd18);
        @(posedge clk);
        input_byte = 8'd36;
        assert (output_byte == 8'd72);
        @(posedge clk);
        input_byte = 8'd44;
        assert (output_byte == 8'd88);
        @(posedge clk);
        input_byte = 8'd161;
        assert (output_byte == 8'd89);
        @(posedge clk);
        input_byte = 8'd169;
        assert (output_byte == 8'd73);
        @(posedge clk);
        input_byte = 8'd238;
        assert (output_byte == 8'd199);
        @(posedge clk);
        input_byte = 8'd25;
        assert (output_byte == 8'd50);
        @(posedge clk);
        input_byte = 8'd63;
        assert (output_byte == 8'd126);
        @(posedge clk);
        input_byte = 8'd200;
        assert (output_byte == 8'd139);
        @(posedge clk);
        input_byte = 8'd187;
        assert (output_byte == 8'd109);
        @(posedge clk);
        input_byte = 8'd136;
        assert (output_byte == 8'd11);
        @(posedge clk);
        input_byte = 8'd41;
        assert (output_byte == 8'd82);
        @(posedge clk);
        input_byte = 8'd26;
        assert (output_byte == 8'd52);
        @(posedge clk);
        input_byte = 8'd11;
        assert (output_byte == 8'd22);
        @(posedge clk);
        input_byte = 8'd191;
        assert (output_byte == 8'd101);
        @(posedge clk);
        input_byte = 8'd172;
        assert (output_byte == 8'd67);
        @(posedge clk);
        input_byte = 8'd24;
        assert (output_byte == 8'd48);
        @(posedge clk);
        input_byte = 8'd55;
        assert (output_byte == 8'd110);
        @(posedge clk);
        input_byte = 8'd174;
        assert (output_byte == 8'd71);
        @(posedge clk);
        input_byte = 8'd68;
        assert (output_byte == 8'd136);
        @(posedge clk);
        input_byte = 8'd221;
        assert (output_byte == 8'd161);
        @(posedge clk);
        input_byte = 8'd102;
        assert (output_byte == 8'd204);
        @(posedge clk);
        input_byte = 8'd103;
        assert (output_byte == 8'd206);
        @(posedge clk);
        input_byte = 8'd149;
        assert (output_byte == 8'd49);
        @(posedge clk);
        input_byte = 8'd148;
        assert (output_byte == 8'd51);
        @(posedge clk);
        input_byte = 8'd135;
        assert (output_byte == 8'd21);
        @(posedge clk);
        input_byte = 8'd159;
        assert (output_byte == 8'd37);
        @(posedge clk);
        input_byte = 8'd153;
        assert (output_byte == 8'd41);
        @(posedge clk);
        input_byte = 8'd129;
        assert (output_byte == 8'd25);
        @(posedge clk);
        input_byte = 8'd37;
        assert (output_byte == 8'd74);
        @(posedge clk);
        input_byte = 8'd42;
        assert (output_byte == 8'd84);
        @(posedge clk);
        input_byte = 8'd4;
        assert (output_byte == 8'd8);
        @(posedge clk);
        input_byte = 8'd11;
        assert (output_byte == 8'd22);
        @(posedge clk);
        input_byte = 8'd129;
        assert (output_byte == 8'd25);
        @(posedge clk);
        input_byte = 8'd188;
        assert (output_byte == 8'd99);
        @(posedge clk);
        input_byte = 8'd74;
        assert (output_byte == 8'd148);
        @(posedge clk);
        input_byte = 8'd119;
        assert (output_byte == 8'd238);
        @(posedge clk);
        input_byte = 8'd78;
        assert (output_byte == 8'd156);
        @(posedge clk);
        input_byte = 8'd95;
        assert (output_byte == 8'd190);
        @(posedge clk);
        input_byte = 8'd242;
        assert (output_byte == 8'd255);
        @(posedge clk);
        input_byte = 8'd227;
        assert (output_byte == 8'd221);
        @(posedge clk);
        input_byte = 8'd246;
        assert (output_byte == 8'd247);
        @(posedge clk);
        input_byte = 8'd224;
        assert (output_byte == 8'd219);
        @(posedge clk);
        input_byte = 8'd13;
        assert (output_byte == 8'd26);
        @(posedge clk);
        input_byte = 8'd27;
        assert (output_byte == 8'd54);
        @(posedge clk);
        input_byte = 8'd154;
        assert (output_byte == 8'd47);
        @(posedge clk);
        input_byte = 8'd78;
        assert (output_byte == 8'd156);
        @(posedge clk);
        input_byte = 8'd98;
        assert (output_byte == 8'd196);
        @(posedge clk);
        input_byte = 8'd182;
        assert (output_byte == 8'd119);
        @(posedge clk);
        input_byte = 8'd106;
        assert (output_byte == 8'd212);
        @(posedge clk);
        input_byte = 8'd203;
        assert (output_byte == 8'd141);
        @(posedge clk);
        input_byte = 8'd151;
        assert (output_byte == 8'd53);
        @(posedge clk);
        input_byte = 8'd54;
        assert (output_byte == 8'd108);
        @(posedge clk);
        input_byte = 8'd81;
        assert (output_byte == 8'd162);
        @(posedge clk);
        input_byte = 8'd197;
        assert (output_byte == 8'd145);
        @(posedge clk);
        input_byte = 8'd37;
        assert (output_byte == 8'd74);
        @(posedge clk);
        input_byte = 8'd177;
        assert (output_byte == 8'd121);
        @(posedge clk);
        input_byte = 8'd217;
        assert (output_byte == 8'd169);
        @(posedge clk);
        input_byte = 8'd187;
        assert (output_byte == 8'd109);
        @(posedge clk);
        input_byte = 8'd71;
        assert (output_byte == 8'd142);
        @(posedge clk);
        input_byte = 8'd37;
        assert (output_byte == 8'd74);
        @(posedge clk);
        input_byte = 8'd123;
        assert (output_byte == 8'd246);
        @(posedge clk);
        input_byte = 8'd111;
        assert (output_byte == 8'd222);
        @(posedge clk);
        input_byte = 8'd54;
        assert (output_byte == 8'd108);
        @(posedge clk);
        input_byte = 8'd34;
        assert (output_byte == 8'd68);
        @(posedge clk);
        input_byte = 8'd253;
        assert (output_byte == 8'd225);
        @(posedge clk);
        input_byte = 8'd49;
        assert (output_byte == 8'd98);
        @(posedge clk);
        input_byte = 8'd48;
        assert (output_byte == 8'd96);
        @(posedge clk);
        input_byte = 8'd252;
        assert (output_byte == 8'd227);
        @(posedge clk);
        input_byte = 8'd214;
        assert (output_byte == 8'd183);
        @(posedge clk);
        input_byte = 8'd135;
        assert (output_byte == 8'd21);
        @(posedge clk);
        input_byte = 8'd174;
        assert (output_byte == 8'd71);
        @(posedge clk);
        input_byte = 8'd255;
        assert (output_byte == 8'd229);
        @(posedge clk);
        input_byte = 8'd237;
        assert (output_byte == 8'd193);
        @(posedge clk);
        input_byte = 8'd198;
        assert (output_byte == 8'd151);
        @(posedge clk);
        input_byte = 8'd68;
        assert (output_byte == 8'd136);
        @(posedge clk);
        input_byte = 8'd111;
        assert (output_byte == 8'd222);
        @(posedge clk);
        input_byte = 8'd60;
        assert (output_byte == 8'd120);
        @(posedge clk);
        input_byte = 8'd169;
        assert (output_byte == 8'd73);
        @(posedge clk);
        input_byte = 8'd185;
        assert (output_byte == 8'd105);
        @(posedge clk);
        input_byte = 8'd44;
        assert (output_byte == 8'd88);
        @(posedge clk);
        input_byte = 8'd21;
        assert (output_byte == 8'd42);
        @(posedge clk);
        input_byte = 8'd48;
        assert (output_byte == 8'd96);
        @(posedge clk);
        input_byte = 8'd21;
        assert (output_byte == 8'd42);
        @(posedge clk);
        input_byte = 8'd48;
        assert (output_byte == 8'd96);
        @(posedge clk);
        input_byte = 8'd181;
        assert (output_byte == 8'd113);
        @(posedge clk);
        input_byte = 8'd189;
        assert (output_byte == 8'd97);
        @(posedge clk);
        input_byte = 8'd137;
        assert (output_byte == 8'd9);
        @(posedge clk);
        input_byte = 8'd129;
        assert (output_byte == 8'd25);
        @(posedge clk);
        input_byte = 8'd79;
        assert (output_byte == 8'd158);
        @(posedge clk);
        input_byte = 8'd25;
        assert (output_byte == 8'd50);
        @(posedge clk);
        input_byte = 8'd67;
        assert (output_byte == 8'd134);
        @(posedge clk);
        input_byte = 8'd21;
        assert (output_byte == 8'd42);
    end
always #1 clk = ~clk;
endmodule
