`timescale 1ns / 1ps

module AES_GCM_Session_Sequencer_wrapper #(
    parameter C_AXI_ADDR_WIDTH  = 8,
    parameter C_AXI_DATA_WIDTH  = 32
)(
    input  wire         aclk,
    input  wire         aresetn,

    input  wire [127:0] s_axis_tdata,
    input  wire [15:0]  s_axis_tkeep,
    input  wire         s_axis_tvalid,
    output wire         s_axis_tready,
    input  wire         s_axis_tlast,

    output wire [127:0] m_axis_tdata,
    output wire [15:0]  m_axis_tkeep,
    output wire         m_axis_tvalid,
    input  wire         m_axis_tready,
    output wire         m_axis_tlast,

    input  wire [C_AXI_ADDR_WIDTH-1:0] s_axi_awaddr,
    input  wire [2:0]                  s_axi_awprot,
    input  wire                        s_axi_awvalid,
    output wire                        s_axi_awready,
    input  wire [C_AXI_DATA_WIDTH-1:0] s_axi_wdata,
    input  wire [3:0]                  s_axi_wstrb,
    input  wire                        s_axi_wvalid,
    output wire                        s_axi_wready,
    output wire [1:0]                  s_axi_bresp,
    output wire                        s_axi_bvalid,
    input  wire                        s_axi_bready,
    input  wire [C_AXI_ADDR_WIDTH-1:0] s_axi_araddr,
    input  wire [2:0]                  s_axi_arprot,
    input  wire                        s_axi_arvalid,
    output wire                        s_axi_arready,
    output wire [C_AXI_DATA_WIDTH-1:0] s_axi_rdata,
    output wire [1:0]                  s_axi_rresp,
    output wire                        s_axi_rvalid,
    input  wire                        s_axi_rready,

    output wire [C_AXI_ADDR_WIDTH-1:0] m_axi_awaddr,
    output wire [2:0]                  m_axi_awprot,
    output wire                        m_axi_awvalid,
    input  wire                        m_axi_awready,
    output wire [C_AXI_DATA_WIDTH-1:0] m_axi_wdata,
    output wire [3:0]                  m_axi_wstrb,
    output wire                        m_axi_wvalid,
    input  wire                        m_axi_wready,
    input  wire [1:0]                  m_axi_bresp,
    input  wire                        m_axi_bvalid,
    output wire                        m_axi_bready,
    output wire [C_AXI_ADDR_WIDTH-1:0] m_axi_araddr,
    output wire [2:0]                  m_axi_arprot,
    output wire                        m_axi_arvalid,
    input  wire                        m_axi_arready,
    input  wire [C_AXI_DATA_WIDTH-1:0] m_axi_rdata,
    input  wire [1:0]                  m_axi_rresp,
    input  wire                        m_axi_rvalid,
    output wire                        m_axi_rready,

    output wire [31:0]  cfg_session_id,
    output wire [15:0]  cfg_stream_id,
    output wire [7:0]   cfg_payload_type,
    output wire [7:0]   cfg_key_id,
    output wire [15:0]  cfg_payload_bytes,
    output wire [63:0]  cfg_nonce_counter,
    output wire         cfg_enable,

    output wire [63:0]  nonce_counter_out,
    output wire         seq_busy
);

    AES_GCM_Session_Sequencer #(
        .C_AXI_ADDR_WIDTH(C_AXI_ADDR_WIDTH),
        .C_AXI_DATA_WIDTH(C_AXI_DATA_WIDTH)
    ) u_seq (
        .aclk               (aclk),
        .aresetn            (aresetn),

        .s_axis_tdata       (s_axis_tdata),
        .s_axis_tkeep       (s_axis_tkeep),
        .s_axis_tvalid      (s_axis_tvalid),
        .s_axis_tready      (s_axis_tready),
        .s_axis_tlast       (s_axis_tlast),

        .m_axis_tdata       (m_axis_tdata),
        .m_axis_tkeep       (m_axis_tkeep),
        .m_axis_tvalid      (m_axis_tvalid),
        .m_axis_tready      (m_axis_tready),
        .m_axis_tlast       (m_axis_tlast),

        .S_AXI_AWADDR       (s_axi_awaddr),
        .S_AXI_AWPROT       (s_axi_awprot),
        .S_AXI_AWVALID      (s_axi_awvalid),
        .S_AXI_AWREADY      (s_axi_awready),
        .S_AXI_WDATA        (s_axi_wdata),
        .S_AXI_WSTRB        (s_axi_wstrb),
        .S_AXI_WVALID       (s_axi_wvalid),
        .S_AXI_WREADY       (s_axi_wready),
        .S_AXI_BRESP        (s_axi_bresp),
        .S_AXI_BVALID       (s_axi_bvalid),
        .S_AXI_BREADY       (s_axi_bready),
        .S_AXI_ARADDR       (s_axi_araddr),
        .S_AXI_ARPROT       (s_axi_arprot),
        .S_AXI_ARVALID      (s_axi_arvalid),
        .S_AXI_ARREADY      (s_axi_arready),
        .S_AXI_RDATA        (s_axi_rdata),
        .S_AXI_RRESP        (s_axi_rresp),
        .S_AXI_RVALID       (s_axi_rvalid),
        .S_AXI_RREADY       (s_axi_rready),

        .M_AXI_AWADDR       (m_axi_awaddr),
        .M_AXI_AWPROT       (m_axi_awprot),
        .M_AXI_AWVALID      (m_axi_awvalid),
        .M_AXI_AWREADY      (m_axi_awready),
        .M_AXI_WDATA        (m_axi_wdata),
        .M_AXI_WSTRB        (m_axi_wstrb),
        .M_AXI_WVALID       (m_axi_wvalid),
        .M_AXI_WREADY       (m_axi_wready),
        .M_AXI_BRESP        (m_axi_bresp),
        .M_AXI_BVALID       (m_axi_bvalid),
        .M_AXI_BREADY       (m_axi_bready),
        .M_AXI_ARADDR       (m_axi_araddr),
        .M_AXI_ARPROT       (m_axi_arprot),
        .M_AXI_ARVALID      (m_axi_arvalid),
        .M_AXI_ARREADY      (m_axi_arready),
        .M_AXI_RDATA        (m_axi_rdata),
        .M_AXI_RRESP        (m_axi_rresp),
        .M_AXI_RVALID       (m_axi_rvalid),
        .M_AXI_RREADY       (m_axi_rready),

        .cfg_session_id     (cfg_session_id),
        .cfg_stream_id      (cfg_stream_id),
        .cfg_payload_type   (cfg_payload_type),
        .cfg_key_id         (cfg_key_id),
        .cfg_payload_bytes  (cfg_payload_bytes),
        .cfg_nonce_counter  (cfg_nonce_counter),
        .cfg_enable         (cfg_enable),

        .nonce_counter_out  (nonce_counter_out),
        .seq_busy           (seq_busy)
    );

endmodule
